linux:
  tags:
    - linux
  script:
    - python setup.py bdist_wheel

  artifacts:
    paths:
      - dist/*.whl

# osx:
#   tags:
#     - osx
#   script:
#     - python setup.py bdist_wheel
# 
#   artifacts:
#     paths:
#       - dist/*.whl

windows:
  tags:
    - docker
  image:
    name: tshirtman/kpmwine
    entrypoint: [""]
  script:
    - pip install -r requirements.txt
    - /entrypoint.sh python setup.py bdist_wheel

  artifacts:
    paths:
      - dist/*.whl
